Enhance Testing Framework #488 #489 #490 #491 #492
FalkorDB/falkordb-browser pull request #493
Opened 2024-09-24 13:34 UTC by Naseem77

2024-09-25 09:59 UTC, AviAvni requested changes

2024-09-25 10:15 UTC, Naseem77 commented on .env.local.template
> -# Next secrets
this has been deleted by mistake

2024-09-25 10:15 UTC, Naseem77 commented on e2e/tests/auth.setup.ts
> +setup("admin authentication", async () => {
Now the BrowserWrapper functionally creates the page instead of using Playwright's built-in methods.

2024-09-25 10:16 UTC, Naseem77 commented on e2e/tests/graph.spec.ts
> +        // { name: 'readwrite' },
Yes, temporarily to make my tests pass because a bug has been opened, which is: #483 and #484

2024-09-25 10:21 UTC, Naseem77 commented on e2e/tests/settingsUsers.spec.ts
> +    test("@admin Add one new user -> validating user exists in the users list", async () => {
No, we don't have any tests that check this, we should have a test which check if other users can access settings page, and we should have other tests which checks if other users can use the api to make any changes in the settings

2024-09-25 10:21 UTC, Naseem77 commented on e2e/tests/settingsConfig.spec.ts
> +        test(`@admin Modify ${roles.maxQueuedQueries} via API validation via UI: Input value: ${input} description: ${description}`, async () => {
No, we don't have any tests that check this, we should have a test which check if other users can access settings page, and we should have other tests which checks if other users can use the api to make any changes in the settings

2024-09-25 10:22 UTC, Naseem77 commented on e2e/tests/signOut.spec.ts
> +const roles = [
yes, i will change it.

2024-10-07 14:31 UTC, AviAvni approved these changes

2024-10-07 14:39 UTC, merged